/*
 * %W% %E% Hamza Yasin
 *
 * Copyright (c) 2017-2018 Miranz Technology. All Rights Reserved.
 *
 * This software is the confidential and proprietary information of Miranz
 * technology. You shall not disclose such Confidential Information and 
 * shall use it only in accordance with the terms of the license agreement 
 * you entered into with Miranz.
 *
 */
package com.hr.charles.app.chinhoyihr.ui.views.salaryslips;


import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import com.hr.charles.app.chinhoyihr.model.SalarySlip;

/**
 * @version 1.10 25 Aug 2017
 * @author Hamza Yasin
 */
public class SalarySlipDetail extends javax.swing.JDialog {

    /**
     * Creates new form SalarySlipDetail
     * @param parent
     * @param modal
     * @param salarySlip
     */
    public SalarySlipDetail(java.awt.Frame parent, boolean modal, SalarySlip salarySlip) {
        super(parent, modal);
        initComponents();
        
        idLabel.setText(salarySlip.getId()+"");
        nameLabel.setText(salarySlip.getName());
        positionLabel.setText(salarySlip.getPost());
        salaryMonthLabel.setText(salarySlip.getMonthName());
        workingDaysLabel.setText(salarySlip.getTotalWorkingDays()+"");
        advanceLabel.setText(salarySlip.getAdvance()+"");
        deductionLabel.setText(salarySlip.getDeduction()+"");
        netSalaryLabel.setText(salarySlip.getNetSalary()+"");
        issueDateLabel.setText(salarySlip.getDate());
        totalAmountLabel.setText(salarySlip.getGross()+"");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Sihle Manqele
    private void initComponents() {
        jPanel1 = new JPanel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        jLabel10 = new JLabel();
        jSeparator1 = new JSeparator();
        jLabel11 = new JLabel();
        jLabel12 = new JLabel();
        idLabel = new JLabel();
        nameLabel = new JLabel();
        positionLabel = new JLabel();
        salaryMonthLabel = new JLabel();
        workingDaysLabel = new JLabel();
        advanceLabel = new JLabel();
        deductionLabel = new JLabel();
        netSalaryLabel = new JLabel();
        issueDateLabel = new JLabel();
        totalAmountLabel = new JLabel();
        jLabel23 = new JLabel();
        closeButton = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        Container contentPane = getContentPane();

        //======== jPanel1 ========
        {
            jPanel1.setBackground(Color.white);
            jPanel1.setBorder ( new javax . swing. border .CompoundBorder ( new javax . swing. border .TitledBorder ( new javax . swing.
            border .EmptyBorder ( 0, 0 ,0 , 0) ,  "JF\u006frmD\u0065sig\u006eer \u0045val\u0075ati\u006fn" , javax. swing .border . TitledBorder. CENTER
            ,javax . swing. border .TitledBorder . BOTTOM, new java. awt .Font ( "Dia\u006cog", java .awt . Font
            . BOLD ,12 ) ,java . awt. Color .red ) ,jPanel1. getBorder () ) ); jPanel1. addPropertyChangeListener(
            new java. beans .PropertyChangeListener ( ){ @Override public void propertyChange (java . beans. PropertyChangeEvent e) { if( "\u0062ord\u0065r"
            .equals ( e. getPropertyName () ) )throw new RuntimeException( ) ;} } );
            jPanel1.setLayout(null);

            //---- jLabel2 ----
            jLabel2.setFont(new Font("Sitka Small", Font.BOLD, 40));
            jLabel2.setText("HR MANAGEMENT SYSTEM");
            jPanel1.add(jLabel2);
            jLabel2.setBounds(new Rectangle(new Point(40, 20), jLabel2.getPreferredSize()));

            //---- jLabel3 ----
            jLabel3.setFont(new Font("Tahoma", Font.BOLD, 18));
            jLabel3.setForeground(new Color(0, 102, 204));
            jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
            jLabel3.setText("Auto Generated Salary Details");
            jPanel1.add(jLabel3);
            jLabel3.setBounds(30, 90, 451, jLabel3.getPreferredSize().height);

            //---- jLabel4 ----
            jLabel4.setFont(new Font("Tahoma", Font.BOLD, 14));
            jLabel4.setText("ID:");
            jPanel1.add(jLabel4);
            jLabel4.setBounds(new Rectangle(new Point(31, 185), jLabel4.getPreferredSize()));

            //---- jLabel5 ----
            jLabel5.setFont(new Font("Tahoma", Font.BOLD, 14));
            jLabel5.setText("Name:");
            jPanel1.add(jLabel5);
            jLabel5.setBounds(new Rectangle(new Point(31, 230), jLabel5.getPreferredSize()));

            //---- jLabel6 ----
            jLabel6.setFont(new Font("Tahoma", Font.BOLD, 14));
            jLabel6.setText("Position:");
            jPanel1.add(jLabel6);
            jLabel6.setBounds(new Rectangle(new Point(31, 275), jLabel6.getPreferredSize()));

            //---- jLabel7 ----
            jLabel7.setFont(new Font("Tahoma", Font.BOLD, 14));
            jLabel7.setText("Salary Month:");
            jPanel1.add(jLabel7);
            jLabel7.setBounds(new Rectangle(new Point(31, 320), jLabel7.getPreferredSize()));

            //---- jLabel8 ----
            jLabel8.setFont(new Font("Tahoma", Font.BOLD, 14));
            jLabel8.setText("Working Days:");
            jPanel1.add(jLabel8);
            jLabel8.setBounds(new Rectangle(new Point(31, 365), jLabel8.getPreferredSize()));

            //---- jLabel9 ----
            jLabel9.setFont(new Font("Tahoma", Font.BOLD, 14));
            jLabel9.setText("Advance:");
            jPanel1.add(jLabel9);
            jLabel9.setBounds(new Rectangle(new Point(31, 410), jLabel9.getPreferredSize()));

            //---- jLabel10 ----
            jLabel10.setFont(new Font("Tahoma", Font.BOLD, 14));
            jLabel10.setText("Deduction:");
            jPanel1.add(jLabel10);
            jLabel10.setBounds(new Rectangle(new Point(31, 459), jLabel10.getPreferredSize()));
            jPanel1.add(jSeparator1);
            jSeparator1.setBounds(0, 122, 1019, 30);

            //---- jLabel11 ----
            jLabel11.setFont(new Font("Tahoma", Font.BOLD, 14));
            jLabel11.setText("Net Salary:");
            jPanel1.add(jLabel11);
            jLabel11.setBounds(new Rectangle(new Point(636, 185), jLabel11.getPreferredSize()));

            //---- jLabel12 ----
            jLabel12.setFont(new Font("Tahoma", Font.BOLD, 14));
            jLabel12.setText("Issue Date:");
            jPanel1.add(jLabel12);
            jLabel12.setBounds(new Rectangle(new Point(636, 230), jLabel12.getPreferredSize()));

            //---- idLabel ----
            idLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
            idLabel.setText("Issue Date:");
            jPanel1.add(idLabel);
            idLabel.setBounds(new Rectangle(new Point(190, 185), idLabel.getPreferredSize()));

            //---- nameLabel ----
            nameLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
            nameLabel.setText("Issue Date:");
            jPanel1.add(nameLabel);
            nameLabel.setBounds(new Rectangle(new Point(190, 230), nameLabel.getPreferredSize()));

            //---- positionLabel ----
            positionLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
            positionLabel.setText("Issue Date:");
            jPanel1.add(positionLabel);
            positionLabel.setBounds(new Rectangle(new Point(190, 275), positionLabel.getPreferredSize()));

            //---- salaryMonthLabel ----
            salaryMonthLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
            salaryMonthLabel.setText("Issue Date:");
            jPanel1.add(salaryMonthLabel);
            salaryMonthLabel.setBounds(new Rectangle(new Point(190, 320), salaryMonthLabel.getPreferredSize()));

            //---- workingDaysLabel ----
            workingDaysLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
            workingDaysLabel.setText("Issue Date:");
            jPanel1.add(workingDaysLabel);
            workingDaysLabel.setBounds(new Rectangle(new Point(190, 365), workingDaysLabel.getPreferredSize()));

            //---- advanceLabel ----
            advanceLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
            advanceLabel.setText("Issue Date:");
            jPanel1.add(advanceLabel);
            advanceLabel.setBounds(new Rectangle(new Point(190, 410), advanceLabel.getPreferredSize()));

            //---- deductionLabel ----
            deductionLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
            deductionLabel.setText("Issue Date:");
            jPanel1.add(deductionLabel);
            deductionLabel.setBounds(new Rectangle(new Point(190, 459), deductionLabel.getPreferredSize()));

            //---- netSalaryLabel ----
            netSalaryLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
            netSalaryLabel.setText("Issue Date:");
            jPanel1.add(netSalaryLabel);
            netSalaryLabel.setBounds(new Rectangle(new Point(790, 185), netSalaryLabel.getPreferredSize()));

            //---- issueDateLabel ----
            issueDateLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
            issueDateLabel.setText("Issue Date:");
            jPanel1.add(issueDateLabel);
            issueDateLabel.setBounds(new Rectangle(new Point(790, 230), issueDateLabel.getPreferredSize()));

            //---- totalAmountLabel ----
            totalAmountLabel.setFont(new Font("Tahoma", Font.BOLD, 18));
            totalAmountLabel.setForeground(new Color(0, 102, 0));
            totalAmountLabel.setText("Rs/10000000");
            jPanel1.add(totalAmountLabel);
            totalAmountLabel.setBounds(new Rectangle(new Point(790, 332), totalAmountLabel.getPreferredSize()));

            //---- jLabel23 ----
            jLabel23.setFont(new Font("Tahoma", Font.BOLD, 18));
            jLabel23.setForeground(new Color(0, 102, 0));
            jLabel23.setText("Total Amount:");
            jPanel1.add(jLabel23);
            jLabel23.setBounds(new Rectangle(new Point(636, 332), jLabel23.getPreferredSize()));

            //---- closeButton ----
            closeButton.setBackground(Color.white);
            closeButton.setFont(new Font("Tahoma", Font.PLAIN, 18));
            closeButton.setText("Close");
            closeButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            closeButton.addActionListener(e -> closeButtonActionPerformed(e));
            jPanel1.add(closeButton);
            closeButton.setBounds(0, 494, 1019, closeButton.getPreferredSize().height);

            {
                // compute preferred size
                Dimension preferredSize = new Dimension();
                for(int i = 0; i < jPanel1.getComponentCount(); i++) {
                    Rectangle bounds = jPanel1.getComponent(i).getBounds();
                    preferredSize.width = Math.max(bounds.x + bounds.width, preferredSize.width);
                    preferredSize.height = Math.max(bounds.y + bounds.height, preferredSize.height);
                }
                Insets insets = jPanel1.getInsets();
                preferredSize.width += insets.right;
                preferredSize.height += insets.bottom;
                jPanel1.setMinimumSize(preferredSize);
                jPanel1.setPreferredSize(preferredSize);
            }
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Sihle Manqele
    private JPanel jPanel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JLabel jLabel10;
    private JSeparator jSeparator1;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel idLabel;
    private JLabel nameLabel;
    private JLabel positionLabel;
    private JLabel salaryMonthLabel;
    private JLabel workingDaysLabel;
    private JLabel advanceLabel;
    private JLabel deductionLabel;
    private JLabel netSalaryLabel;
    private JLabel issueDateLabel;
    private JLabel totalAmountLabel;
    private JLabel jLabel23;
    private JButton closeButton;
    // End of variables declaration//GEN-END:variables
}
