/*
 * %W% %E% Hamza Yasin
 *
 * Copyright (c) 2017-2018 Miranz Technology. All Rights Reserved.
 *
 * This software is the confidential and proprietary information of Miranz
 * technology. You shall not disclose such Confidential Information and 
 * shall use it only in accordance with the terms of the license agreement 
 * you entered into with Miranz.
 *
 */
package com.hr.charles.app.chinhoyihr.ui.views.salaryslips;

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;

import com.hr.charles.app.chinhoyihr.domain.SalaryHandling;

import javax.swing.JOptionPane;

/**
 * @version 1.10 25 Aug 2017
 * @author Hamza Yasin
 */
public class SalarySlip extends javax.swing.JPanel {

    /**
     * Creates new form SalarySlip
     */
    public SalarySlip() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Sihle Manqele
    private void initComponents() {
        jLabel1 = new JLabel();
        jLabel4 = new JLabel();
        idTextField = new JTextField();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        advanceTextField = new JTextField();
        jLabel7 = new JLabel();
        deductionTextField = new JTextField();
        generateSlipButton = new JButton();
        jLabel8 = new JLabel();
        salaryMonth = new JComboBox<>();
        salaryDays = new JComboBox<>();

        //======== this ========
        setBackground(Color.white);
        setBorder (new javax. swing. border. CompoundBorder( new javax .swing .border .TitledBorder (
        new javax. swing. border. EmptyBorder( 0, 0, 0, 0) , "JF\u006frmD\u0065sig\u006eer \u0045val\u0075ati\u006fn"
        , javax. swing. border. TitledBorder. CENTER, javax. swing. border. TitledBorder. BOTTOM
        , new java .awt .Font ("Dia\u006cog" ,java .awt .Font .BOLD ,12 )
        , java. awt. Color. red) , getBorder( )) );  addPropertyChangeListener (
        new java. beans. PropertyChangeListener( ){ @Override public void propertyChange (java .beans .PropertyChangeEvent e
        ) {if ("\u0062ord\u0065r" .equals (e .getPropertyName () )) throw new RuntimeException( )
        ; }} );

        //---- jLabel1 ----
        jLabel1.setFont(new Font("Tahoma", Font.BOLD, 20));
        jLabel1.setForeground(new Color(0, 102, 204));
        jLabel1.setText("Salary Slips");
        jLabel1.setToolTipText("");

        //---- jLabel4 ----
        jLabel4.setFont(new Font("Tahoma", Font.BOLD, 14));
        jLabel4.setText("ID: ");

        //---- idTextField ----
        idTextField.setFont(new Font("Tahoma", Font.PLAIN, 14));
        idTextField.setHorizontalAlignment(SwingConstants.CENTER);

        //---- jLabel5 ----
        jLabel5.setFont(new Font("Tahoma", Font.BOLD, 14));
        jLabel5.setText("Days:");

        //---- jLabel6 ----
        jLabel6.setFont(new Font("Tahoma", Font.BOLD, 14));
        jLabel6.setText("Advance:");

        //---- advanceTextField ----
        advanceTextField.setFont(new Font("Tahoma", Font.PLAIN, 14));
        advanceTextField.setHorizontalAlignment(SwingConstants.CENTER);

        //---- jLabel7 ----
        jLabel7.setFont(new Font("Tahoma", Font.BOLD, 14));
        jLabel7.setText("Deduction:");

        //---- deductionTextField ----
        deductionTextField.setFont(new Font("Tahoma", Font.PLAIN, 14));
        deductionTextField.setHorizontalAlignment(SwingConstants.CENTER);

        //---- generateSlipButton ----
        generateSlipButton.setBackground(Color.white);
        generateSlipButton.setFont(new Font("Tahoma", Font.BOLD, 22));
        generateSlipButton.setForeground(new Color(0, 102, 0));
        generateSlipButton.setText("Generate Slip");
        generateSlipButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        generateSlipButton.addActionListener(e -> generateSlipButtonActionPerformed(e));

        //---- jLabel8 ----
        jLabel8.setFont(new Font("Tahoma", Font.BOLD, 14));
        jLabel8.setText("Salary Month:");

        //---- salaryMonth ----
        salaryMonth.setFont(new Font("Tahoma", Font.PLAIN, 13));
        salaryMonth.setModel(new DefaultComboBoxModel<>(new String[] {
            "Jan",
            "Feb",
            "Mar",
            "Aprl",
            "May",
            "Jun",
            "Jul",
            "Aug",
            "Sept",
            "Oct",
            "Nov",
            "Dec"
        }));
        salaryMonth.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        //---- salaryDays ----
        salaryDays.setFont(new Font("Tahoma", Font.PLAIN, 13));
        salaryDays.setModel(new DefaultComboBoxModel<>(new String[] {
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28",
            "29",
            "30",
            "31"
        }));
        salaryDays.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        GroupLayout layout = new GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup()
                .addGroup(layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addGroup(layout.createParallelGroup()
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addGroup(layout.createParallelGroup()
                                .addComponent(generateSlipButton, GroupLayout.PREFERRED_SIZE, 215, GroupLayout.PREFERRED_SIZE)
                                .addComponent(salaryMonth, GroupLayout.PREFERRED_SIZE, 172, GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(123, 123, 123)
                            .addComponent(idTextField, GroupLayout.PREFERRED_SIZE, 172, GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(111, 111, 111)
                            .addComponent(salaryDays, GroupLayout.PREFERRED_SIZE, 172, GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(85, 85, 85)
                            .addComponent(advanceTextField, GroupLayout.PREFERRED_SIZE, 172, GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(74, 74, 74)
                            .addComponent(deductionTextField, GroupLayout.PREFERRED_SIZE, 172, GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup()
                .addGroup(layout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addComponent(jLabel1)
                    .addGap(50, 50, 50)
                    .addGroup(layout.createParallelGroup()
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel4))
                        .addComponent(idTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGap(45, 45, 45)
                    .addGroup(layout.createParallelGroup()
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jLabel5))
                        .addComponent(salaryDays, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGap(46, 46, 46)
                    .addGroup(layout.createParallelGroup()
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel6))
                        .addComponent(advanceTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGap(56, 56, 56)
                    .addGroup(layout.createParallelGroup()
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel7))
                        .addComponent(deductionTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGap(59, 59, 59)
                    .addGroup(layout.createParallelGroup()
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jLabel8))
                        .addComponent(salaryMonth, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGap(37, 37, 37)
                    .addComponent(generateSlipButton, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void generateSlipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateSlipButtonActionPerformed
        try{
             java.util.Calendar cal = new java.util.GregorianCalendar();
            SalaryHandling.save(new com.hr.charles.app.chinhoyihr.model.SalarySlip(Integer.parseInt(idTextField.getText()),
                    "", "", salaryMonth.getSelectedItem().toString(), 
                    Integer.parseInt(salaryDays.getSelectedItem().toString()),
                    Double.parseDouble(advanceTextField.getText()),
                    Double.parseDouble(deductionTextField.getText()), 1, 
                    cal.getTime().toString()));
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Invalid Data Entered.");
        }
    }//GEN-LAST:event_generateSlipButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Sihle Manqele
    private JLabel jLabel1;
    private JLabel jLabel4;
    private JTextField idTextField;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JTextField advanceTextField;
    private JLabel jLabel7;
    private JTextField deductionTextField;
    private JButton generateSlipButton;
    private JLabel jLabel8;
    private JComboBox<String> salaryMonth;
    private JComboBox<String> salaryDays;
    // End of variables declaration//GEN-END:variables
}
