/*
 * %W% %E% Hamza Yasin
 *
 * Copyright (c) 2017-2018 Miranz Technology. All Rights Reserved.
 *
 * This software is the confidential and proprietary information of Miranz
 * technology. You shall not disclose such Confidential Information and 
 * shall use it only in accordance with the terms of the license agreement 
 * you entered into with Miranz.
 *
 */
package com.hr.charles.app.chinhoyihr.ui.views.dailywork;

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;

import com.hr.charles.app.chinhoyihr.domain.DailyTaskHandling;
import com.hr.charles.app.chinhoyihr.model.DailyTask;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
/*
 * @version 1.10 25 Aug 2017
 * @author Hamza Yasin
 */
public class DailyWorkPanel extends javax.swing.JPanel {

    /**
     * Creates new form DailyWorkPanel
     */
    public DailyWorkPanel() {
        initComponents();
        DailyTaskHandling.load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Sihle Manqele
    private void initComponents() {
        jLabel1 = new JLabel();
        jLabel4 = new JLabel();
        idTextField = new JTextField();
        jLabel5 = new JLabel();
        attendenceTextField = new JTextField();
        jLabel6 = new JLabel();
        jScrollPane1 = new JScrollPane();
        workTextPane = new JTextPane();
        jButton1 = new JButton();
        clearButton = new JButton();
        jLabel2 = new JLabel();

        //======== this ========
        setBackground(Color.white);
        setPreferredSize(new Dimension(950, 393));
        setBorder (new javax. swing. border. CompoundBorder( new javax .swing .border .TitledBorder (new javax
        . swing. border. EmptyBorder( 0, 0, 0, 0) , "JFor\u006dDesi\u0067ner \u0045valu\u0061tion", javax. swing
        . border. TitledBorder. CENTER, javax. swing. border. TitledBorder. BOTTOM, new java .awt .
        Font ("Dia\u006cog" ,java .awt .Font .BOLD ,12 ), java. awt. Color. red
        ) , getBorder( )) );  addPropertyChangeListener (new java. beans. PropertyChangeListener( ){ @Override
        public void propertyChange (java .beans .PropertyChangeEvent e) {if ("bord\u0065r" .equals (e .getPropertyName (
        ) )) throw new RuntimeException( ); }} );

        //---- jLabel1 ----
        jLabel1.setFont(new Font("Tahoma", Font.BOLD, 20));
        jLabel1.setForeground(new Color(0, 102, 204));
        jLabel1.setText("Daily Work");
        jLabel1.setToolTipText("");

        //---- jLabel4 ----
        jLabel4.setFont(new Font("Tahoma", Font.BOLD, 14));
        jLabel4.setText("ID: ");

        //---- idTextField ----
        idTextField.setFont(new Font("Tahoma", Font.PLAIN, 14));
        idTextField.setHorizontalAlignment(SwingConstants.CENTER);

        //---- jLabel5 ----
        jLabel5.setFont(new Font("Tahoma", Font.BOLD, 14));
        jLabel5.setText("Attendence:");

        //---- attendenceTextField ----
        attendenceTextField.setFont(new Font("Tahoma", Font.PLAIN, 14));
        attendenceTextField.setHorizontalAlignment(SwingConstants.CENTER);

        //---- jLabel6 ----
        jLabel6.setFont(new Font("Tahoma", Font.BOLD, 14));
        jLabel6.setText("Daily Work:");

        //======== jScrollPane1 ========
        {

            //---- workTextPane ----
            workTextPane.setFont(new Font("Tahoma", Font.PLAIN, 14));
            jScrollPane1.setViewportView(workTextPane);
        }

        //---- jButton1 ----
        jButton1.setBackground(Color.white);
        jButton1.setFont(new Font("Tahoma", Font.BOLD, 17));
        jButton1.setForeground(new Color(0, 102, 0));
        jButton1.setText("Submit");
        jButton1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jButton1.addActionListener(e -> jButton1ActionPerformed(e));

        //---- clearButton ----
        clearButton.setBackground(Color.white);
        clearButton.setFont(new Font("Tahoma", Font.BOLD, 17));
        clearButton.setForeground(new Color(153, 0, 0));
        clearButton.setText("Clear");
        clearButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        clearButton.addActionListener(e -> clearButtonActionPerformed(e));

        GroupLayout layout = new GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup()
                .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addGroup(layout.createParallelGroup()
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup()
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup()
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 124, GroupLayout.PREFERRED_SIZE)
                                            .addGap(52, 52, 52)
                                            .addComponent(clearButton, GroupLayout.PREFERRED_SIZE, 123, GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 335, GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(attendenceTextField)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(64, 64, 64)
                            .addComponent(idTextField, GroupLayout.PREFERRED_SIZE, 172, GroupLayout.PREFERRED_SIZE)))
                    .addGap(835, 835, 835))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup()
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(33, 33, 33)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(idTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup()
                        .addGroup(layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(jLabel5))
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(attendenceTextField, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup()
                        .addGroup(layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addComponent(jLabel6)))
                    .addGap(67, 67, 67)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                        .addComponent(clearButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        //---- jLabel2 ----
        jLabel2.setFont(new Font("Tahoma", Font.BOLD, 14));
        jLabel2.setText("ID: ");
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        idTextField.setText("");
        attendenceTextField.setText("");
        workTextPane.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{          
            DailyTaskHandling.save(getData());
            JOptionPane.showMessageDialog(null, "Daily Work Posted");
       }catch(HeadlessException e){
           JOptionPane.showMessageDialog(null, "Not Posted. " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public DailyTask getData(){
        int id = Integer.parseInt(idTextField.getText());
        
        String attndnc = attendenceTextField.getText();
        String work = workTextPane.getText();
        java.util.Calendar cal = new java.util.GregorianCalendar();
        return  new DailyTask(id, attndnc, work, cal.getTime().toString(), "Not Available");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Sihle Manqele
    private JLabel jLabel1;
    private JLabel jLabel4;
    private JTextField idTextField;
    private JLabel jLabel5;
    private JTextField attendenceTextField;
    private JLabel jLabel6;
    private JScrollPane jScrollPane1;
    private JTextPane workTextPane;
    private JButton jButton1;
    private JButton clearButton;
    private JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
